import Header from "../Header";
import Head from "next/head";
import { StyledMain } from "./Layout.Styled";

export default function Layout({
  children,
  isActive,
  setActive,
  onToggleClass,
}) {
  return (
    <>
      <Head>
        <title>Marcel Epp</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header
        isActive={isActive}
        setActive={setActive}
        onToggleClass={onToggleClass}
      />
      <StyledMain>{children}</StyledMain>
    </>
  );
}
